### ISSUE TITLE
new releases?

### ISSUE THREAD

**Issue by oscarbg** [google/gapid-dev-releases#1]
New releases have been missing for three months already..
thanks..

**Comment by hevrard** [comment]
Most of the folks working on GAPID are now working on AGI: https://github.com/google/agi, I would recommend switching to AGI if possible. AGI has [regular dev-releases](https://github.com/google/agi-dev-releases/releases).

There is no active plan to keep on doing new GAPID dev-releases.

**Comment by oscarbg** [comment]
thanks..
